# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ip99qOyfKw22vGVNaPVa4lwnG51FWjbw
"""

# Commented out IPython magic to ensure Python compatibility.
# Step 1: Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Enable inline plotting
# %matplotlib inline

# Step 2: Load Dataset (replace with your file)
from google.colab import files
uploaded = files.upload()

# Assuming the uploaded file is a CSV
df = pd.read_csv(next(iter(uploaded)))

# Step 3: Initial Inspection
print("Shape:", df.shape)
df.head()

# Step 4: Data Cleaning
# Check for missing values
print("\nMissing Values:\n", df.isnull().sum())

# Fill or drop missing values
df.fillna(method='ffill', inplace=True)

# Drop duplicates
df.drop_duplicates(inplace=True)

# Step 5: Feature Engineering (example: tenure in months)
df['hire_date'] = pd.to_datetime(df['hire_date'])
df['tenure_months'] = (pd.to_datetime('today') - df['hire_date']).dt.days // 30

# Step 6: Univariate Analysis
plt.figure(figsize=(8,5))
sns.histplot(df['performance_score'], bins=10, kde=True)
plt.title("Distribution of Performance Scores")
plt.show()

# Step 7: Bivariate Analysis
plt.figure(figsize=(10,6))
sns.boxplot(x='department', y='performance_score', data=df)
plt.xticks(rotation=45)
plt.title("Performance by Department")
plt.show()

# Step 8: Correlation Heatmap
plt.figure(figsize=(10,8))
corr = df.select_dtypes(include=[np.number]).corr()
sns.heatmap(corr, annot=True, cmap='coolwarm', fmt=".2f")
plt.title("Correlation Matrix")
plt.show()

# Step 9: Productivity Trend (optional - if date available)
# df['date'] = pd.to_datetime(df['date'])
# df.set_index('date')['tasks_completed'].resample('M').mean().plot()
# plt.title("Monthly Average Tasks Completed")
# plt.show()